//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailGen.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizibleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizibleStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailGen.Properties.LocalizibleStrings", typeof(LocalizibleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attempting to connect to EWS....
        /// </summary>
        internal static string AttemptingConnectEws {
            get {
                return ResourceManager.GetString("AttemptingConnectEws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticate.
        /// </summary>
        internal static string Auth {
            get {
                return ResourceManager.GetString("Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticate : Please enter your credentials in UPN format (email or domain \\name).
        /// </summary>
        internal static string AuthInvalidUpn {
            get {
                return ResourceManager.GetString("AuthInvalidUpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autodiscover complete..
        /// </summary>
        internal static string AutodiscoverComplete {
            get {
                return ResourceManager.GetString("AutodiscoverComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add selected to mail list.
        /// </summary>
        internal static string BtnAddSelectedToMailList {
            get {
                return ResourceManager.GetString("BtnAddSelectedToMailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear filter.
        /// </summary>
        internal static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        internal static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save all.
        /// </summary>
        internal static string BtnSaveAll {
            get {
                return ResourceManager.GetString("BtnSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot connect to EWS.
        /// </summary>
        internal static string CannotConnectToEws {
            get {
                return ResourceManager.GetString("CannotConnectToEws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create EWS trace file.
        /// </summary>
        internal static string CannotCreateTrace {
            get {
                return ResourceManager.GetString("CannotCreateTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot delete contact .
        /// </summary>
        internal static string CannotDeleteContact {
            get {
                return ResourceManager.GetString("CannotDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot get contact list.
        /// </summary>
        internal static string CannotGetContactList {
            get {
                return ResourceManager.GetString("CannotGetContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot get event template list.
        /// </summary>
        internal static string CannotGetEventTemplateList {
            get {
                return ResourceManager.GetString("CannotGetEventTemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot get mail template list.
        /// </summary>
        internal static string CannotGetMailTemplateList {
            get {
                return ResourceManager.GetString("CannotGetMailTemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot load stored contacts.
        /// </summary>
        internal static string CannotGetStoredContacts {
            get {
                return ResourceManager.GetString("CannotGetStoredContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot get template folder ({0} in conf.json).
        /// </summary>
        internal static string CannotGetTemplateFolder {
            get {
                return ResourceManager.GetString("CannotGetTemplateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot process menu item.
        /// </summary>
        internal static string CannotProcessMenuItem {
            get {
                return ResourceManager.GetString("CannotProcessMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receiver.
        /// </summary>
        internal static string ColumnCanReceive {
            get {
                return ResourceManager.GetString("ColumnCanReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sender.
        /// </summary>
        internal static string ColumnCanSend {
            get {
                return ResourceManager.GetString("ColumnCanSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject.
        /// </summary>
        internal static string ColumnSubject {
            get {
                return ResourceManager.GetString("ColumnSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credential confirmation failed : .
        /// </summary>
        internal static string ConfirmationFailed {
            get {
                return ResourceManager.GetString("ConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The credentials were not authenticated..
        /// </summary>
        internal static string CredNotAuth {
            get {
                return ResourceManager.GetString("CredNotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want delete selected rows?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email (errormailadress in conf.json) for debug mail undefined..
        /// </summary>
        internal static string ErrorAdressUndefined {
            get {
                return ResourceManager.GetString("ErrorAdressUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when create mail from template .
        /// </summary>
        internal static string ErrorCreateFromTemplate {
            get {
                return ResourceManager.GetString("ErrorCreateFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while generating messages.
        /// </summary>
        internal static string ErrorGenMailMsg {
            get {
                return ResourceManager.GetString("ErrorGenMailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Error text: 
        ///.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unhandled exception.
        /// </summary>
        internal static string ErrorUnhandledException {
            get {
                return ResourceManager.GetString("ErrorUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EWS Login.
        /// </summary>
        internal static string EwsLogin {
            get {
                return ResourceManager.GetString("EwsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder with name {0} ({1} in conf.json) not found/found several.
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your EWS login and password.
        /// </summary>
        internal static string InputYourCred {
            get {
                return ResourceManager.GetString("InputYourCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language code (lang in conf.json) is not integer ({0}).
        /// </summary>
        internal static string LangCodeIsNotInteger {
            get {
                return ResourceManager.GetString("LangCodeIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown language code {0} (lang in conf.json).
        /// </summary>
        internal static string LangUnrecognized {
            get {
                return ResourceManager.GetString("LangUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count:.
        /// </summary>
        internal static string LbCount {
            get {
                return ResourceManager.GetString("LbCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search:.
        /// </summary>
        internal static string LbSearch {
            get {
                return ResourceManager.GetString("LbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After change language need restart application. Do it now?.
        /// </summary>
        internal static string MessageNeedRestart {
            get {
                return ResourceManager.GetString("MessageNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created {0} of {1}.
        /// </summary>
        internal static string MsgCreatedOf {
            get {
                return ResourceManager.GetString("MsgCreatedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sending finished....
        /// </summary>
        internal static string MsgSendingFinished {
            get {
                return ResourceManager.GetString("MsgSendingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sending started....
        /// </summary>
        internal static string MsgSendingStarted {
            get {
                return ResourceManager.GetString("MsgSendingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The login has a maximum length of {0} characters..
        /// </summary>
        internal static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password has a maximum length of {0} characters..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recipients count &lt;= 0.
        /// </summary>
        internal static string RecipientsCount {
            get {
                return ResourceManager.GetString("RecipientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Would you like to retry connecting to EWS?.
        /// </summary>
        internal static string RetryConnection {
            get {
                return ResourceManager.GetString("RetryConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Senders count &lt;= 0.
        /// </summary>
        internal static string SendersCount {
            get {
                return ResourceManager.GetString("SendersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sender (errormailfrom in conf.json) for error mail undefined..
        /// </summary>
        internal static string SenderUndefined {
            get {
                return ResourceManager.GetString("SenderUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smtp server undefined (smtpserver in conf.json).
        ///The generated letters can not be send..
        /// </summary>
        internal static string SmtpServerUndefined {
            get {
                return ResourceManager.GetString("SmtpServerUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smtp port (smtpport in conf.json) is not integer value.
        /// </summary>
        internal static string SmtpUndefined {
            get {
                return ResourceManager.GetString("SmtpUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Sending debug mail disabled.
        ///Continue execution?.
        /// </summary>
        internal static string StandartEnd {
            get {
                return ResourceManager.GetString("StandartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Using Autodiscover to find EWS URL for {0}. Please wait... .
        /// </summary>
        internal static string StartAutodiscover {
            get {
                return ResourceManager.GetString("StartAutodiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully connected to EWS..
        /// </summary>
        internal static string SuccConnection {
            get {
                return ResourceManager.GetString("SuccConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The target has a maximum length of {0} characters..
        /// </summary>
        internal static string TargetNameLength {
            get {
                return ResourceManager.GetString("TargetNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The target cannot be a null value..
        /// </summary>
        internal static string TargetNotNull {
            get {
                return ResourceManager.GetString("TargetNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try load data from default folder.
        /// </summary>
        internal static string TryLoadFromDefault {
            get {
                return ResourceManager.GetString("TryLoadFromDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unhandled condition : .
        /// </summary>
        internal static string UnhandledCondition {
            get {
                return ResourceManager.GetString("UnhandledCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot recognize EWS version from value .
        /// </summary>
        internal static string UnrecognizedEwsVersion {
            get {
                return ResourceManager.GetString("UnrecognizedEwsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
