//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizibleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizibleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailGen.Properties.LocalizibleStrings", typeof(LocalizibleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to EWS....
        /// </summary>
        internal static string AttemptingConnectEws {
            get {
                return ResourceManager.GetString("AttemptingConnectEws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        internal static string Auth {
            get {
                return ResourceManager.GetString("Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate : Please enter your credentials in UPN format (email or domain \\name).
        /// </summary>
        internal static string AuthInvalidUpn {
            get {
                return ResourceManager.GetString("AuthInvalidUpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodiscover complete..
        /// </summary>
        internal static string AutodiscoverComplete {
            get {
                return ResourceManager.GetString("AutodiscoverComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected to mail list.
        /// </summary>
        internal static string BtnAddSelectedToMailList {
            get {
                return ResourceManager.GetString("BtnAddSelectedToMailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        internal static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        internal static string BtnSaveAll {
            get {
                return ResourceManager.GetString("BtnSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to EWS.
        /// </summary>
        internal static string CannotConnectToEws {
            get {
                return ResourceManager.GetString("CannotConnectToEws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create EWS trace file.
        /// </summary>
        internal static string CannotCreateTrace {
            get {
                return ResourceManager.GetString("CannotCreateTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete contact .
        /// </summary>
        internal static string CannotDeleteContact {
            get {
                return ResourceManager.GetString("CannotDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get contact list.
        /// </summary>
        internal static string CannotGetContactList {
            get {
                return ResourceManager.GetString("CannotGetContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get event template list.
        /// </summary>
        internal static string CannotGetEventTemplateList {
            get {
                return ResourceManager.GetString("CannotGetEventTemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get mail template list.
        /// </summary>
        internal static string CannotGetMailTemplateList {
            get {
                return ResourceManager.GetString("CannotGetMailTemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load stored contacts.
        /// </summary>
        internal static string CannotGetStoredContacts {
            get {
                return ResourceManager.GetString("CannotGetStoredContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get template folder ({0} in conf.json).
        /// </summary>
        internal static string CannotGetTemplateFolder {
            get {
                return ResourceManager.GetString("CannotGetTemplateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process menu item.
        /// </summary>
        internal static string CannotProcessMenuItem {
            get {
                return ResourceManager.GetString("CannotProcessMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string ColumnCanReceive {
            get {
                return ResourceManager.GetString("ColumnCanReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string ColumnCanSend {
            get {
                return ResourceManager.GetString("ColumnCanSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ColumnSubject {
            get {
                return ResourceManager.GetString("ColumnSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential confirmation failed : .
        /// </summary>
        internal static string ConfirmationFailed {
            get {
                return ResourceManager.GetString("ConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials were not authenticated..
        /// </summary>
        internal static string CredNotAuth {
            get {
                return ResourceManager.GetString("CredNotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want delete selected rows?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (errormailadress in conf.json) for debug mail undefined..
        /// </summary>
        internal static string ErrorAdressUndefined {
            get {
                return ResourceManager.GetString("ErrorAdressUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Error text: 
        ///.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWS Login.
        /// </summary>
        internal static string EwsLogin {
            get {
                return ResourceManager.GetString("EwsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with name {0} ({1} in conf.json) not found/found several.
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your EWS login and password.
        /// </summary>
        internal static string InputYourCred {
            get {
                return ResourceManager.GetString("InputYourCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code (lang in conf.json) is not integer ({0}).
        /// </summary>
        internal static string LangCodeIsNotInteger {
            get {
                return ResourceManager.GetString("LangCodeIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown language code {0} (lang in conf.json).
        /// </summary>
        internal static string LangUnrecognized {
            get {
                return ResourceManager.GetString("LangUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        internal static string LbCount {
            get {
                return ResourceManager.GetString("LbCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string LbSearch {
            get {
                return ResourceManager.GetString("LbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After change language need restart application. Do it now?.
        /// </summary>
        internal static string MessageNeedRestart {
            get {
                return ResourceManager.GetString("MessageNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login has a maximum length of {0} characters..
        /// </summary>
        internal static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has a maximum length of {0} characters..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients count &lt;= 0.
        /// </summary>
        internal static string RecipientsCount {
            get {
                return ResourceManager.GetString("RecipientsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to retry connecting to EWS?.
        /// </summary>
        internal static string RetryConnection {
            get {
                return ResourceManager.GetString("RetryConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senders count &lt;= 0.
        /// </summary>
        internal static string SendersCount {
            get {
                return ResourceManager.GetString("SendersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender (errormailfrom in conf.json) for error mail undefined..
        /// </summary>
        internal static string SenderUndefined {
            get {
                return ResourceManager.GetString("SenderUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp server undefined (smtpserver in conf.json).
        ///The generated letters can not be send..
        /// </summary>
        internal static string SmtpServerUndefined {
            get {
                return ResourceManager.GetString("SmtpServerUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp port (smtpport in conf.json) is not integer value.
        /// </summary>
        internal static string SmtpUndefined {
            get {
                return ResourceManager.GetString("SmtpUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Sending debug mail disabled.
        ///Continue execution?.
        /// </summary>
        internal static string StandartEnd {
            get {
                return ResourceManager.GetString("StandartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Autodiscover to find EWS URL for {0}. Please wait... .
        /// </summary>
        internal static string StartAutodiscover {
            get {
                return ResourceManager.GetString("StartAutodiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to EWS..
        /// </summary>
        internal static string SuccConnection {
            get {
                return ResourceManager.GetString("SuccConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target has a maximum length of {0} characters..
        /// </summary>
        internal static string TargetNameLength {
            get {
                return ResourceManager.GetString("TargetNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target cannot be a null value..
        /// </summary>
        internal static string TargetNotNull {
            get {
                return ResourceManager.GetString("TargetNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try load data from default folder.
        /// </summary>
        internal static string TryLoadFromDefault {
            get {
                return ResourceManager.GetString("TryLoadFromDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled condition : .
        /// </summary>
        internal static string UnhandledCondition {
            get {
                return ResourceManager.GetString("UnhandledCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot recognize EWS version from value .
        /// </summary>
        internal static string UnrecognizedEwsVersion {
            get {
                return ResourceManager.GetString("UnrecognizedEwsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
